# Generated by Django 5.0.6 on 2024-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketsegment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymarketsegment',
            name='search_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
