# Generated by Django 5.0.6 on 2024-07-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0002_companymarketsegment_raw_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketsegment',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymarketsegment',
            name='raw_industries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketingai.companymarketsegment')),
            ],
        ),
    ]
