# Generated by Django 5.0.6 on 2024-07-11 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0003_companymarketsegment_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketsegment',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
