# Generated by Django 5.0.6 on 2024-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0004_companymarketsegment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketsegment',
            name='conversation_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymarketsegment',
            name='raw_messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
