# Generated by Django 5.0.6 on 2024-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0005_companymarketsegment_conversation_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
