# Generated by Django 5.0.6 on 2024-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0006_alter_company_legal_name_alter_company_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketsegment',
            name='final_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymarketsegment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
