# Generated by Django 5.0.6 on 2024-07-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0007_companymarketsegment_final_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='problem_statement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('customers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketingai.company')),
            ],
        ),
    ]
