# Generated by Django 5.0.6 on 2024-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0008_company_customer_list_company_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='customer_comment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
