# Generated by Django 5.0.6 on 2024-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0009_casestudy_customer_comment_casestudy_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
