# Generated by Django 5.0.6 on 2024-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0010_alter_casestudy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='details_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
