# Generated by Django 5.0.6 on 2024-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0011_company_details_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsuggestions',
            name='case_study_ids',
            field=models.JSONField(default=[]),
        ),
    ]
