# Generated by Django 5.0.6 on 2024-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0012_emailsuggestions_case_study_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsuggestions',
            name='case_study_ids',
            field=models.TextField(),
        ),
    ]
