# Generated by Django 5.0.6 on 2024-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0013_alter_emailsuggestions_case_study_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsuggestions',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailsuggestions',
            name='sequence_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailsuggestions',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
