# Generated by Django 5.0.6 on 2024-08-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0014_emailsuggestions_order_emailsuggestions_sequence_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things_not_to_change', models.TextField(blank=True, null=True)),
                ('email_json', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketingai.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMailPersonalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_linkedin_url', models.TextField()),
                ('company_domain', models.TextField()),
                ('raw_person_data', models.JSONField(blank=True, null=True)),
                ('linkedin_data', models.JSONField(blank=True, null=True)),
                ('personalised_email_copy', models.JSONField(blank=True, default=[], null=True)),
                ('email_sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketingai.emailsequence')),
            ],
        ),
    ]
