# Generated by Django 5.0.6 on 2024-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingai', '0015_emailsequence_emailmailpersonalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='company_post_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='post_found',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='raw_company_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='sequence_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmailpersonalisation',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
